name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    # services:
      # mysql:
      #   image: mysql:latest
      #   options: >-
      #     --health-cmd='mysqladmin ping --silent'
      #     --health-interval=10s
      #     --health-timeout=5s
      #     --health-retries=3
      #   env:
      #     MYSQL_ROOT_PASSWORD: rootpassword
      #     MYSQL_DATABASE: testdb  # 数据库名为 testdb
      #   ports:
      #     - 3306:3306
      #   #options: --health-timeout=5m

    steps:
    # 设置 MySQL
    - name: Set up MySQL
      uses: samin/mysql-action@v1
      with:
        mysql database: 'dbtest' # Optional, default value is "test". The specified database which will be create
        mysql root password: rootpassword # Required if "mysql user" is empty, default is empty. The root superuser password

    # 检出你的代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 安装依赖
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake make g++ libmysqlclient-dev

    # 等待 MySQL 完全初始化
    - name: Wait for MySQL to be ready
      run: |
        for i in {30..0}; do
          if mysqladmin ping -h 127.0.0.1 --silent; then
            break
          fi
          echo 'Waiting for MySQL...'
          sleep 1
        done
        if [ "$i" = 0 ]; then
          echo 'MySQL did not start in time' >&2
          exit 1
        fi

    # 创建 user 表
    - name: Create user table
      run: |
        mysql -h 127.0.0.1 -u root -prootpassword -e "USE testdb; \
        CREATE TABLE IF NOT EXISTS user ( \
        username CHAR(50) NULL, \
        password CHAR(50) NULL \
        ) ENGINE=InnoDB;"

    # 执行 CMake 生成
    - name: Build with CMake
      run: |
        cmake -S . -B build
        cmake --build build

    # 启动服务器
    - name: Start Server
      run: |
        cd build
        nohup ./Server &

    # 检查服务器是否正常运行，监听指定端口
    - name: Check if server is running
      run: |
        for i in {30..0}; do
          if nc -zv 127.0.0.1 8080; then
            echo "Server is running on port 8080"
            break
          fi
          echo 'Waiting for Server to start...'
          sleep 1
        done
        if [ "$i" = 0 ]; then
          echo 'Server did not start in time' >&2
          exit 1
        fi
